version: '3.3'
volumes:
  mongodbdata:
services:
  mongo:
    image: "mongo:3.0"
    ports: 
      - "27017:27017"  # For debugging purposes
    command: --smallfiles
    volumes:
      - mongodbdata:/data/db
  rabbit:
    image: "rabbitmq:3-management"
    ports: 
      - "15672:15672"  # For debugging purposes
      - "5672:5672"  # For debugging purposes
  api:
    build: 
      context: api/
      dockerfile: ./Dockerfile
    secrets:
      - source: conf
        target: conf.json
    depends_on:
      - "rabbit"
      - "mongo"
    ports:
      - 3000:3000
  cartographer:
    build: 
      context: cartographer/
      dockerfile: ./Dockerfile
    depends_on:
      - "rabbit"
      - "mongo"
